### ISSUE TITLE
The plugin "auto-assign" didn't export a Plugin instance

### ISSUE THREAD

**Issue by sbruchmann** [shuhei/babel-plugin-auto-assign#1]
Hello @shuhei,

I just installed `babel-plugin-auto-assign@0.1.0` and I am trying to use it with `babel-core@5.8.24`.

Full stack trace:

```
TypeError: The plugin "auto-assign" didn't export a Plugin instance
    at PluginManager.validate (/Users/sbruchmann/dev/micah/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/sbruchmann/dev/micah/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/sbruchmann/dev/micah/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/sbruchmann/dev/micah/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/sbruchmann/dev/micah/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.transpile [as .js] (/Users/sbruchmann/dev/micah/app/babel.js:27:22)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Corresponding code:

``` javascript
'use strict';

var babel = require('babel-core')
var fs = require('fs')

var options = {
  externalHelpers: true,
  sourceMaps: 'inline',
  optional: [
    'es7.decorators'
  ],
  plugins: [
    'auto-assign'
  ]
}

function register() {
  Object.defineProperty(require.extensions, '.js', {
    value: transpile,
    writable: false
  })
}

function transpile(module, filePath) {
  var sourceCode = fs.readFileSync(filePath, 'utf8')

  sourceCode = babel.transform(sourceCode, options).code
  module._compile(sourceCode, filePath)
}

module.exports = {
  register: register
}
```

**Comment by shuhei** [comment]
@sbruchmann Thanks for reporting. How do you use your `register` function? I'd like to try it.

I tried the following code, a tweaked version of  your code, and it worked:

```
node ./compile.js
```

compile.js

``` js
'use strict';

var babel = require('babel-core')
var fs = require('fs')

var options = {
  externalHelpers: true,
  sourceMaps: 'inline',
  optional: [
    'es7.decorators'
  ],
  plugins: [
    'auto-assign'
  ]
}

function transpile(filePath) {
  var sourceCode = fs.readFileSync(filePath, 'utf8')

  sourceCode = babel.transform(sourceCode, options).code
  return sourceCode;
  // module._compile(sourceCode, filePath)
}

console.log(transpile('./index.js'));
```

index.js

``` js
@autoAssign
class Hello {
  constructor(foo, bar, baz) {
  }
}
```

**Comment by shuhei** [comment]
I tested the above with Node v0.12.7 and v4.0.0.

**Comment by shuhei** [comment]
Ah, sorry. I pasted wrong code. Updated the comment.

**Comment by sbruchmann** [comment]
**Note**: I’m developing an [electron](https://github.com/atom/electron) app.

I’m using `register()` and `transpile()` to automatically transpile ES6 modules to ES5 on the fly when they are `require`d. In future, this function will cache the transpiled code. For reference, see [atom/electron-starter/src/babel.coffe](https://github.com/atom-archive/electron-starter/blob/bd0926f90ff62a322a2cbf18881bc69e2265fe67/src/babel.coffee#L120)

Because of that, I _have to_ use `module._compile(sourceCode, filePath)`.

**Comment by shuhei** [comment]
Got it. I need an [MCVE](http://stackoverflow.com/help/mcve) to reproduce the error and investigate it because the error means that some setting is wrong. Do you think atom-archive/electron-starter with the plugin setting is the MCVE?

**Comment by sbruchmann** [comment]
~~No, `atom/electron-starter` is definitely not a _MCVE_, since it is written in CoffeeScript. I’ll upload a _MCVE_ as a gist later today.~~

Gotcha! There’s nothing wrong with your code. I’ve _blacklisted_ all `node_modules` when transpiling on the fly and the _bug_ was fixed.

**Comment by shuhei** [comment]
All right, thanks!
